# Generated by Django 3.1.4 on 2021-02-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('raca', models.CharField(max_length=20)),
                ('classe', models.CharField(max_length=20)),
                ('historia', models.TextField(blank=True)),
            ],
        ),
    ]
